// get products
export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';
export const GET_PRODUCTS_CLEANUP = 'GET_PRODUCTS_CLEANUP';

export const LIKED_PRODUCTS_START = 'LIKED_PRODUCTS_START';
export const LIKED_PRODUCTS_SUCCESS = 'LIKED_PRODUCTS_SUCCESS';
export const LIKED_PRODUCTS_FAIL = 'LIKED_PRODUCTS_FAIL';
export const LIKED_PRODUCTS_CLEANUP = 'LIKED_PRODUCTS_CLEANUP';
